# Generated by Django 3.2.9 on 2021-11-19 05:19

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airkorea', models.JSONField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 5, 19, 0, 853993, tzinfo=utc), verbose_name='airkorea date published')),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 5, 19, 0, 853518, tzinfo=utc))),
            ],
        ),
    ]
