# Generated by Django 3.2.9 on 2021-11-22 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211122_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='location',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
